### ISSUE TITLE
`types.d.ts` are not published

### ISSUE THREAD

**Issue by gugahoi** [basiqio/basiq-connect-control#55]
When trying to use this library in a typescript project, it seems to be missing it's types. I can see that there is a very simple declaration for types but it does not seem to be included in the npm package. Is it possible to rectify that?

I've also taken the liberty of actually documenting these config types, feel free to use them if you find it valuable:

```ts
declare module '@basiq/basiq-connect-control' {
  type config = {
    containerId: string
    connect?: boolean
    upload?: boolean
    companyName?: string
    regionOfInstitutions?: 'Australia' | 'New Zealand'
    hideTestBanks?: boolean
    hideBetaBanks?: boolean
  } & (
    | {
        connectLink: string
        userID?: undefined
        token?: undefined
      }
    | {
        connectLink?: undefined
        userID: string
        token: string
      }
  )

  export default function (input: config): void
}
```

Finally, it seems that the README has a typo where it says that `connectLinkId` is a valid prop but the source code is checking for `connectLink`.

**Comment by ashmanmalik** [comment]
Hey @gugahoi Thanks for reaching out. 

We have a new package in place for TypeScript which is here: https://www.npmjs.com/package/@basiq/connect-auth

and we have deprecated this package. I hope this helps :) 

Cheers,
Ash

**Comment by gugahoi** [comment]
Thanks for letting me know @ashmanmalik. It's a little hard to keep track of what is current. It would be good to put this info in the README. I also noticed that `connect-auth` has no github repo linked to it and it's documentation still says to install `basiq-connect-control`.

![image](https://user-images.githubusercontent.com/355877/203190655-3a2c9cc2-37eb-479f-b263-3543da95b6b0.png)

**Comment by ashmanmalik** [comment]
Thanks @gugahoi for pointing that out. We will update Readme but I am sure we have a package for this update, let me chase the team to find this out.

Normally we pushed all changes in our docs change-log which is here: https://api.basiq.io/changelog/august-22

**Comment by ashmanmalik** [comment]
I will be updating the git link on the npm package.
